# 定义类别数(包括背景)
num_classes: 2
classes_weight: [1., 3.5]  # [1., 1., 2.5]
in_channels: [0, 1, 2, 9] # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
in_channels2: [0, 1, 2]
batch_size: 1
num_epochs: 400
unet_base: 32
base_size:  [1408, 992] # [480, 608] # [480, 608] [1360, 1504] [1408, 992](分成六块)  [928, 992](分成9快)[1360, 1504]
unit_size: [700, 600] # 代表一个单元的尺寸，每个单元由四张图片组成，单位是毫米
pixel_shift_ratio: [0, 0]